# Generated by Django 4.2.7 on 2023-12-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NightSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='published')),
                ('student_grade', models.IntegerField()),
                ('student_name', models.CharField(max_length=15)),
            ],
        ),
    ]
