# Generated by Django 4.2.7 on 2023-12-06 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_password'),
        ('afterschool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInformation',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=255)),
                ('class_location', models.CharField(max_length=255)),
                ('class_time', models.SmallIntegerField()),
                ('teacher', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SeatNumber',
            fields=[
                ('number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('seat_number', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserWeekSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon', models.CharField(max_length=5)),
                ('tue', models.CharField(max_length=5)),
                ('wed', models.CharField(max_length=5)),
                ('thr', models.CharField(max_length=5)),
                ('mon_fixed', models.CharField(max_length=5)),
                ('tue_fixed', models.CharField(max_length=5)),
                ('wed_fixed', models.CharField(max_length=5)),
                ('thr_fixed', models.CharField(max_length=5)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
        migrations.DeleteModel(
            name='NightSchedule',
        ),
    ]
