# Generated by Django 4.2.7 on 2023-12-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterschool', '0002_classinformation_seatnumber_supervisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userweekschedule',
            name='mon',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='userweekschedule',
            name='mon_fixed',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='userweekschedule',
            name='thr',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='userweekschedule',
            name='thr_fixed',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='userweekschedule',
            name='tue',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='userweekschedule',
            name='tue_fixed',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='userweekschedule',
            name='wed',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='userweekschedule',
            name='wed_fixed',
            field=models.CharField(max_length=8),
        ),
    ]
