# Generated by Django 4.2.7 on 2023-12-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterschool', '0004_alter_userweekschedule_mon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinformation',
            name='class_time',
            field=models.CharField(max_length=64),
        ),
    ]
