# Generated by Django 4.2.7 on 2023-12-08 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_loginsession_session_alter_user_user_id'),
        ('afterschool', '0007_alter_afterschooluser_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afterschooluser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.user'),
        ),
    ]
