# Generated by Django 4.2.7 on 2023-12-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterschool', '0008_alter_afterschooluser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeminarRoomBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room1', models.CharField(max_length=255)),
                ('room2', models.CharField(max_length=255)),
                ('room3', models.CharField(max_length=255)),
                ('room4', models.CharField(max_length=255)),
                ('room5', models.CharField(max_length=255)),
                ('room6', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
    ]
