# Generated by Django 4.2.7 on 2023-12-10 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afterschool', '0009_seminarroombook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userweekschedule',
            old_name='mon',
            new_name='schedule',
        ),
        migrations.RemoveField(
            model_name='userweekschedule',
            name='thr',
        ),
        migrations.RemoveField(
            model_name='userweekschedule',
            name='tue',
        ),
        migrations.RemoveField(
            model_name='userweekschedule',
            name='wed',
        ),
    ]
