# Generated by Django 4.2.7 on 2023-12-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterschool', '0010_rename_mon_userweekschedule_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinformation',
            name='class_type',
            field=models.CharField(default='none', max_length=64),
        ),
        migrations.AlterField(
            model_name='classinformation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
