# Generated by Django 4.2.7 on 2023-12-12 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterschool', '0011_classinformation_class_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinformation',
            name='class_type',
            field=models.CharField(max_length=64),
        ),
    ]
