# Generated by Django 4.2.7 on 2023-12-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterschool', '0012_alter_classinformation_class_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afterschooluser',
            name='mon_fixed',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='afterschooluser',
            name='thr_fixed',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='afterschooluser',
            name='tue_fixed',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='afterschooluser',
            name='wed_fixed',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='seatnumber',
            name='number',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seminarroombook',
            name='room1',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='seminarroombook',
            name='room2',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='seminarroombook',
            name='room3',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='seminarroombook',
            name='room4',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='seminarroombook',
            name='room5',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='seminarroombook',
            name='room6',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='userweekschedule',
            name='schedule',
            field=models.CharField(max_length=16),
        ),
    ]
