# Generated by Django 4.2.7 on 2023-12-09 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0004_alter_loginsession_session_alter_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DormitoryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=3)),
                ('room', models.SmallIntegerField()),
                ('mon_fixed', models.CharField(max_length=3)),
                ('tue_fixed', models.CharField(max_length=3)),
                ('wed_fixed', models.CharField(max_length=3)),
                ('thr_fixed', models.CharField(max_length=3)),
                ('last_updated', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='NightUserSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(max_length=3)),
                ('date', models.DateField()),
                ('participate', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dormitory.dormitoryuser')),
            ],
        ),
    ]
